#!/usr/bin/zsh

PATH=~/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin

zparseopts -D -E  -- s:=searchTerm c:=categoryTerm

manuD=~/.manu-pages/html/.

_search() {
	searchTerm=$(echo $searchTerm | sed 's/[+ ]/.*/g')
	res=$(ag -l -S "$searchTerm" $manuD/$categoryTerm/)
	if [[ -n $res ]]; then
		res=$(echo $res | peco)
		if [[ $(echo -n $res | wc -m) = 0 ]]; then
			echo "User-Interrupt"
			exit 2
		fi
		elinks $res
	else
		echo "Search >>$searchTerm<< didn't match anything ..."
		exit 1
	fi
}
_promptCat() {
	categoryTerm=$(ls $manuD | peco)
}

searchTerm=$searchTerm[2]
categoryTerm=$categoryTerm[2]

if [[ $(echo -n $categoryTerm | wc -m) = 0 ]]; then
	_promptCat
fi
if [[ $(echo -n $searchTerm | wc -m) = 0 ]]; then
	vared -p 'Search Expression:$> ' -c searchTerm
fi
_search
exit 0
