#!/usr/bin/zsh

PATH=~/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin

getopts s searchOnly

manuD=~/.manu-pages/html

cat=javascript
method=list

_search() {
	vared -p 'Search Expression:$> ' -c search
	search=$(echo $search | sed 's/+/.*/g')
	res=$(ag -l -S "$search" $manuD/$cat/)
	if [[ -n $res ]]; then
		res=$(echo $res | peco)
		elinks $res
	else
		echo "Search >>$search<< didn't match anything ..."
		exit 1
	fi
}
_promptCat() {
	cat=$(ls $manuD | peco)
}
_promptMethod() {
	method=$(echo "search\nlist" | yank-cli -d \n)
}

if [[ -n $searchOnly ]]; then
	_promptCat
	_search
	exit 0
else
	_promptCat
	_promptMethod

	if [[ $method = "search" ]]; then
		_search
	else
		res=$(ls $manuD/$cat | peco)
		elinks $manuD/$cat/$res

	fi
fi

exit 0
